### ISSUE TITLE
After offline/disconnect program crashes

### ISSUE THREAD

**Issue by beaug** [BrenMurrell/slack-audiobot#3]
Here is the output:

[Sun Jun 26 2016 20:55:40 GMT+0000 (UTC)] ERROR Last pong is too old: 14.737
[Sun Jun 26 2016 20:55:40 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
[Sun Jun 26 2016 20:55:41 GMT+0000 (UTC)] INFO Attempting reconnect
[Sun Jun 26 2016 20:55:41 GMT+0000 (UTC)] INFO Connecting...
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Client.emit (events.js:87:13)
    at Client._onLogin (/home/pi/music/slack-audiobot/node_modules/slack-client/src/client.js:74:14)
    at /home/pi/music/slack-audiobot/node_modules/slack-client/src/client.js:2:59
    at ClientRequest.<anonymous> (/home/pi/music/slack-audiobot/node_modules/slack-client/src/client.js:684:18)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:950:16
    at process._tickCallback (node.js:355:11)

**Comment by BrenMurrell** [comment]
Heya! thanks for the feedback. This is a pretty standard issue with the Slack API rather than this software. See https://github.com/slackhq/node-slack-sdk/issues/5 for more deets. I run this with supervisor usually (`supervisor audiotbot.js` instead of `node audiobot.js`). This means the bot will keep trying to connect rather than dying if it can't make a connection to slack.

**Comment by beaug** [comment]
Awesome thanks! Will give it a try
